version: "2"
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
  app:
    build: ./
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/accept-file
    ports:
      - "3000:3000"
    links:
      - db
    env_file: .env
    environment:
      RAILS_ENV: development
volumes:
  postgres-data:
    driver: local
